
runtime:
    computeType: "BUILD_GENERAL1_SMALL"

stages:
    - build

steps:
    BuildApp:
        image: aws/codebuild/standard:4.0
        stage: build
        commands:
            - cd my-app
            - npm install
            - npm run build
        artifacts:
            files:
                build_folder.zip: "my-app/build/"
            json: "package.json"