
runtime:
    computeType: "BUILD_GENERAL1_SMALL"

stages:
    - build

steps:
    BuildApp:
        image: aws/codebuild/standard:4.0
        stage: build
        commands:
            - cd my-app
            - npm install
            - npm run build
        artifacts:
            files:
                json_files.zip: "my-app/build/*.json"
                js_files_zip: "my-app/build/*.js"
                static_files_zip: "my-app/build/static/"
            json: "package.json"