stages:
    - clone
    - build
    - test
    - package-docker
    - package

steps:
    Clone:
        type: git-clone
        stage: clone

    Build:
        image: node:14.8.0-alpine
        title: This is my build step" 
        stage: build
        commands:
            - echo pre build
            - ls -l
            - npm install
    BuildAgain:
        image: node:14.8.0-alpine
        stage: build
        commands:
            - echo post build
            - npm install
        artifacts:
            files:
                package.zip: ./
                file: package.json
            json: schema.json
    Test:
        image: node:14.8.0-alpine
        stage: test
        commands:
            - echo TEST
        artifacts:
            files:
                test-package.zip: ./
                package_file: package.json
            json: package.json

    PackageAppInDocker:
        type: docker-push
        stage: package-docker
        image_name: microtica/pipeline-test
        registry: dockerhub

    Component:
        title: Package Microtica component
        type: component
        stage: package
        cfn_template: cfn-template.json
