
stages:
    - package

steps:
    Component:
        title: Package Microtica component
        stage: package
        commands:
            - echo TEST
        artifacts:
            files:
                package: ./
                cfn_template: cfn-template.json