
stages:
    - package

steps:
    Component:
        title: Package Microtica component
        type: component
        stage: package
        cfn_template: cfn-template.json
        schema: schema.json