
runtime:
    computeType: "BUILD_GENERAL1_SMALL"

stages:
    - build
    - analyse

steps:
    BuildApp:
        image: aws/codebuild/standard:4.0
        stage: build
        commands:
            - ls -l
            - cd my-app
            - npm install
            - npm run build
    PackageApp:
        image: aws/codebuild/standard:4.0
        stage: analyse
        commands:
            - ls -l
            - echo Analysing code...
        artifacts:
            files:
                whole_package.zip: "./"
            json: "package.json"